### PR TITLE
Added support for StringMatchesFormat

### LINKED ISSUE #8: Add support for assertStringMatchesFormat
Hello.

I'm using your lib via https://github.com/jolicode/asynit (ping @joelwurtz)
And I'm also using this [`trait`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Test/VarDumperTestTrait.php#L29)

But unfortunately, the lib does not support the [`assertStringMatchesFormat`](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertStringMatchesFormat)

Could you add support to it please ?

ping @xavierlacot

### PR DESCRIPTION
**Pull request by lyrixx**
Fixes #8

### CODE REVIEW

**Comment by mikey179** [comment]
Thanks for the PR. I adjusted some of the naming to better fit into the project and added tests, integration within the PHPUnit compatibility layer and the docs in the readme.

**Comment by lyrixx** [comment]
Thanks ;)

**Comment by mikey179** [comment]
And now we have a release: https://github.com/mikey179/bovigo-assert/releases/tag/v3.2.0

**Comment by lyrixx** [comment]
:tada:

**Pull request merged**
